# Redmine Xapian is a Redmine plugin to allow attachments searches by content.
#
# Karel Pičman <karel.picman@kontron.com>
#
# This file is part of Redmine Xapian plugin.
#
# Redmine Xapian plugin is free software: you can redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# Redmine Xapian plugin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
# the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with Redmine Xapian plugin. If not, see
# <https://www.gnu.org/licenses/>.

# Rubocop configuration

AllCops:
  TargetRubyVersion: 3.2
  TargetRailsVersion: 7.1
  SuggestExtensions: false

  NewCops: enable

  Exclude:
    - '**/vendor/**/*'

# Rules for Xapian
Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Lint/ScriptPermission:
  Exclude:
    - extra/xapian_indexer.rb

Style/ExpandPathArguments:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either

